title: Summer Institute in Computational Social Sciences - Buenos Aires 2026
subtitle: Taller Procesamiento de Lenguaje Natural y polarización
show_downloads: false
theme: jekyll-theme-cayman
site.url: https://gefero.github.io/factor_data_tuto_NLP_SICSS/
